/**
 * Created by session1 on 10/19/15.
 */



// 3 X 3 (TIC-TAC-TOE) THIS IS GOING TO BE THE SHAPE OF ALL THE PICTURES ADDED TOGETHER

//ROUNDED BOARDERS AROUNG ALL OF THE PICTURES

// HOVER OR ON CLICK THING

//LOOK @ THE STUFF I WROTE DOWN ON THE PIECE OF PAPER IN MY BINDER.